title: Mert Melih Albay
theme: jekyll-theme-minimal
logo: assets/image (2).png
description: |
  albaymertmelih@gmail.com  
  <br>
  <a href="assets/MertMelihAlbay_CV.pdf" class="cv-button" download> Özgeçmişimi İndir (PDF)</a>  
  <br>
  <a href="assets/MertMelihAlbay_CV_ENG.pdf" class="cv-button" download> Download Resume (PDF)</a>
